import { useEffect, useState } from "react";

export default function Insights({ refreshKey, isDark }) {
  const [insights, setInsights] = useState("Loading AI insights...");

  useEffect(() => {
    fetch("http://localhost:5000/api/ai-insights")
      .then((res) => res.json())
      .then((data) => {
        if (data.insights) {
          setInsights(data.insights);
        } else if (data.error) {
          setInsights("AI Error: " + data.error);
        } else {
          setInsights("No AI insights available.");
        }
      })
      .catch(() => {
        setInsights("Failed to load AI insights.");
      });
  }, [refreshKey]);

  return (
    <div
      className={`rounded-3xl border p-6 shadow-[0_10px_30px_rgba(0,0,0,0.12)] backdrop-blur-xl ${
        isDark ? "border-white/10 bg-white/5" : "border-slate-300 bg-white/80"
      }`}
    >
      <div className="mb-5 flex items-center justify-between">
        <h3 className="text-xl font-semibold">AI Insights</h3>
        <span
          className={`rounded-full px-3 py-1 text-xs ${
            isDark
              ? "border border-cyan-400/20 bg-cyan-400/10 text-cyan-300"
              : "border border-cyan-500/20 bg-cyan-100 text-cyan-700"
          }`}
        >
          Generated by AI
        </span>
      </div>

      <div
        className={`rounded-2xl border p-4 ${
          isDark ? "border-white/10 bg-slate-950/40" : "border-slate-200 bg-slate-50"
        }`}
      >
        <pre
          className={`whitespace-pre-wrap text-sm leading-7 ${
            isDark ? "text-slate-200" : "text-slate-700"
          }`}
        >
          {insights}
        </pre>
      </div>
    </div>
  );
}